// <auto-generated />
using System;
using CleanArchitectureCQRS.Infrastructure.EF.Contexts;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace CleanArchitectureCQRS.Infrastructure.EF.Migrations
{
    [DbContext(typeof(WriteDbContext))]
    partial class WriteDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("SampleEntity")
                .HasAnnotation("ProductVersion", "10.0.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("CleanArchitectureCQRS.Domain.Entities.Cash", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("Version")
                        .HasColumnType("int");

                    b.Property<string>("_name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("Name");

                    b.HasKey("Id");

                    b.ToTable("Cash", "SampleEntity");
                });

            modelBuilder.Entity("CleanArchitectureCQRS.Domain.Entities.Customer", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("Version")
                        .HasColumnType("int");

                    b.Property<string>("_email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("Email");

                    b.Property<string>("_name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("Name");

                    b.HasKey("Id");

                    b.ToTable("Customers", "SampleEntity");
                });

            modelBuilder.Entity("CleanArchitectureCQRS.Domain.Entities.CustomerPayment", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("Version")
                        .HasColumnType("int");

                    b.Property<decimal?>("_amount")
                        .HasColumnType("decimal(18,2)")
                        .HasColumnName("Amount");

                    b.Property<Guid>("_cashFlowId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("CashFlowId");

                    b.Property<Guid>("_cashResourceId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("CashResourceId");

                    b.Property<Guid>("_customerId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("CustomerId");

                    b.Property<DateTimeOffset?>("_endWhen")
                        .HasColumnType("datetimeoffset")
                        .HasColumnName("EndWhen");

                    b.Property<Guid>("_externalParticipationId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("ExternalParticipationId");

                    b.Property<DateTimeOffset>("_when")
                        .HasColumnType("datetimeoffset")
                        .HasColumnName("When");

                    b.HasKey("Id");

                    b.ToTable("CustomerPayments", "SampleEntity");
                });

            modelBuilder.Entity("CleanArchitectureCQRS.Domain.Entities.CustomerPaymentCashFlow", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("Version")
                        .HasColumnType("int");

                    b.Property<Guid>("_cashResourceId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("CashResourceId");

                    b.Property<Guid>("_customerPaymentId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("CustomerPaymentId");

                    b.Property<Guid>("_occurrentEndId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("OccurrentEndId");

                    b.Property<Guid>("_resourceEndId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("ResourceEndId");

                    b.HasKey("Id");

                    b.ToTable("CustomerPaymentCashFlows", "SampleEntity");
                });

            modelBuilder.Entity("CleanArchitectureCQRS.Domain.Entities.Employee", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("Version")
                        .HasColumnType("int");

                    b.Property<string>("_email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("Email");

                    b.Property<string>("_name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("Name");

                    b.Property<string>("_socialSecurityNumber")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("SocialSecurityNumber");

                    b.HasKey("Id");

                    b.ToTable("Employees", "SampleEntity");
                });

            modelBuilder.Entity("CleanArchitectureCQRS.Domain.Entities.ItContract", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("Version")
                        .HasColumnType("int");

                    b.Property<decimal?>("_amount")
                        .HasColumnType("decimal(18,2)")
                        .HasColumnName("Amount");

                    b.Property<string>("_departmentCode")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("DepartmentCode");

                    b.Property<DateTimeOffset?>("_endWhen")
                        .HasColumnType("datetimeoffset")
                        .HasColumnName("EndWhen");

                    b.Property<Guid>("_externalParticipationId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("ExternalParticipationId");

                    b.Property<Guid>("_internalParticipationId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("InternalParticipationId");

                    b.Property<Guid>("_responsibleEmployeeId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("ResponsibleEmployeeId");

                    b.Property<string>("_serviceName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("ServiceName");

                    b.Property<Guid>("_vendorId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("VendorId");

                    b.Property<DateTimeOffset>("_when")
                        .HasColumnType("datetimeoffset")
                        .HasColumnName("When");

                    b.HasKey("Id");

                    b.ToTable("ItContracts", "SampleEntity");
                });

            modelBuilder.Entity("CleanArchitectureCQRS.Domain.Entities.Item", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("Version")
                        .HasColumnType("int");

                    b.Property<string>("_name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("Name");

                    b.HasKey("Id");

                    b.ToTable("Items", "SampleEntity");
                });

            modelBuilder.Entity("CleanArchitectureCQRS.Domain.Entities.PaysFor", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("Version")
                        .HasColumnType("int");

                    b.Property<Guid>("_firstEventId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("SaleId");

                    b.Property<Guid>("_secondEventId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("CustomerPaymentId");

                    b.HasKey("Id");

                    b.HasIndex("_firstEventId", "_secondEventId")
                        .IsUnique();

                    b.ToTable("PaysFor", "SampleEntity");
                });

            modelBuilder.Entity("CleanArchitectureCQRS.Domain.Entities.Sale", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("Version")
                        .HasColumnType("int");

                    b.Property<decimal?>("_amount")
                        .HasColumnType("decimal(18,2)")
                        .HasColumnName("Amount");

                    b.Property<Guid>("_customerId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("CustomerId");

                    b.Property<Guid>("_employeeId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("EmployeeId");

                    b.Property<DateTimeOffset?>("_endWhen")
                        .HasColumnType("datetimeoffset")
                        .HasColumnName("EndWhen");

                    b.Property<Guid>("_externalParticipationId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("ExternalParticipationId");

                    b.Property<Guid>("_internalParticipationId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("InternalParticipationId");

                    b.Property<DateTimeOffset>("_when")
                        .HasColumnType("datetimeoffset")
                        .HasColumnName("When");

                    b.HasKey("Id");

                    b.ToTable("Sales", "SampleEntity");
                });

            modelBuilder.Entity("CleanArchitectureCQRS.Domain.Entities.SalesLine", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("Version")
                        .HasColumnType("int");

                    b.Property<Guid>("_itemId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("ItemId");

                    b.Property<Guid>("_occurrentEndId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("OccurrentEndId");

                    b.Property<decimal>("_quantity")
                        .HasColumnType("decimal(18,2)")
                        .HasColumnName("Quantity");

                    b.Property<Guid>("_resourceEndId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("ResourceEndId");

                    b.Property<Guid>("_saleId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("SaleId");

                    b.Property<decimal>("_unitPrice")
                        .HasColumnType("decimal(18,2)")
                        .HasColumnName("UnitPrice");

                    b.HasKey("Id");

                    b.HasIndex("_saleId");

                    b.ToTable("SalesLines", "SampleEntity");
                });

            modelBuilder.Entity("CleanArchitectureCQRS.Domain.Entities.SalesOrder", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("Version")
                        .HasColumnType("int");

                    b.Property<decimal?>("_amount")
                        .HasColumnType("decimal(18,2)")
                        .HasColumnName("Amount");

                    b.Property<Guid>("_customerId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("CustomerId");

                    b.Property<Guid>("_employeeId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("EmployeeId");

                    b.Property<DateTimeOffset?>("_endWhen")
                        .HasColumnType("datetimeoffset")
                        .HasColumnName("EndWhen");

                    b.Property<Guid>("_externalParticipationId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("ExternalParticipationId");

                    b.Property<Guid>("_internalParticipationId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("InternalParticipationId");

                    b.Property<DateTimeOffset>("_when")
                        .HasColumnType("datetimeoffset")
                        .HasColumnName("When");

                    b.HasKey("Id");

                    b.ToTable("SalesOrders", "SampleEntity");
                });

            modelBuilder.Entity("CleanArchitectureCQRS.Domain.Entities.SalesOrderLine", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("Version")
                        .HasColumnType("int");

                    b.Property<Guid>("_itemId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("ItemId");

                    b.Property<Guid>("_occurrentEndId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("OccurrentEndId");

                    b.Property<decimal>("_quantity")
                        .HasColumnType("decimal(18,2)")
                        .HasColumnName("Quantity");

                    b.Property<Guid>("_resourceEndId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("ResourceEndId");

                    b.Property<Guid>("_salesOrderId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("SalesOrderId");

                    b.Property<decimal>("_unitPrice")
                        .HasColumnType("decimal(18,2)")
                        .HasColumnName("UnitPrice");

                    b.HasKey("Id");

                    b.HasIndex("_salesOrderId");

                    b.ToTable("SalesOrderLines", "SampleEntity");
                });

            modelBuilder.Entity("CleanArchitectureCQRS.Domain.Entities.SampleEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("Version")
                        .HasColumnType("int");

                    b.Property<string>("_destination")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("Destination");

                    b.Property<string>("_name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("Name");

                    b.HasKey("Id");

                    b.ToTable("SampleEntity", "SampleEntity");
                });

            modelBuilder.Entity("CleanArchitectureCQRS.Domain.Entities.Vendor", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("Version")
                        .HasColumnType("int");

                    b.Property<string>("_email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("Email");

                    b.Property<string>("_name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("Name");

                    b.HasKey("Id");

                    b.ToTable("Vendors", "SampleEntity");
                });

            modelBuilder.Entity("CleanArchitectureCQRS.Domain.ValueObjects.SampleEntityItem", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("IsTaken")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<long>("Quantity")
                        .HasColumnType("bigint");

                    b.Property<Guid>("SampleEntityId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("SampleEntityId");

                    b.ToTable("SampleEntityItems", "SampleEntity");
                });

            modelBuilder.Entity("CleanArchitectureCQRS.Domain.Entities.SalesLine", b =>
                {
                    b.HasOne("CleanArchitectureCQRS.Domain.Entities.Sale", null)
                        .WithMany("_salesLines")
                        .HasForeignKey("_saleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("CleanArchitectureCQRS.Domain.Entities.SalesOrderLine", b =>
                {
                    b.HasOne("CleanArchitectureCQRS.Domain.Entities.SalesOrder", null)
                        .WithMany("_salesOrderLines")
                        .HasForeignKey("_salesOrderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("CleanArchitectureCQRS.Domain.ValueObjects.SampleEntityItem", b =>
                {
                    b.HasOne("CleanArchitectureCQRS.Domain.Entities.SampleEntity", null)
                        .WithMany("_items")
                        .HasForeignKey("SampleEntityId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("CleanArchitectureCQRS.Domain.Entities.Sale", b =>
                {
                    b.Navigation("_salesLines");
                });

            modelBuilder.Entity("CleanArchitectureCQRS.Domain.Entities.SalesOrder", b =>
                {
                    b.Navigation("_salesOrderLines");
                });

            modelBuilder.Entity("CleanArchitectureCQRS.Domain.Entities.SampleEntity", b =>
                {
                    b.Navigation("_items");
                });
#pragma warning restore 612, 618
        }
    }
}
